name: Build Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create Docker image
        run: |
          docker build -t cpp-builder .

      - name: Run and build incide container
        run: |
          mkdir -p logs
          docker run --rm \
            -v $(pwd):/app \
            -v $(pwd)/logs:/logs \
            cpp-builder \
            sh -c "cd /app && cmake . && make > /logs/build.log 2>&1"

      - name: Upload compilation log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: logs/build.log
